export const CONF = {
  DEFAULT_START_SIZE: 10,
  DEFAULT_SPEED: 1,
  BREAK_POINT_FULL_HD_SCREEN: "1920px",
  BREAK_POINT_SMALL_SCREEN: "880px",
  MAX_ARRAY_SIZE: 100,
  MIN_ARRAY_SIZE: 4,
  MAX_SPEED: 350,
  MIN_SPEED: 1,
  DEFAULT_ALGORTHIM: "Insertion Sort"
}
